#!/bin/bash

if [ -z ${SUMO_NAME} ] || [ -z ${SUMO_CATEGORY} ]; then
    echo "SUMO_NAME or SUMO_CATEGORY environment variable(s) not set, exiting"
    exit 1
fi

TEMPLATE="{
    \"api.version\": \"v1\",
    \"sources\": [
        {
            \"sourceType\": \"LocalFile\",
            \"name\": \"${SUMO_NAME}\",
            \"pathExpression\": \"/tmp/clogs/events.log\",
            \"category\": \"${SUMO_CATEGORY}\",
            \"useAutolineMatching\": false,
            \"multilineProcessingEnabled\": false
        }
    ]
}"

echo "Writing /etc/sumo-sources.json:"
echo "${TEMPLATE}"
echo ${TEMPLATE} > /etc/sumo-sources.json

echo "Starting sumologic..."
source /run.sh "$@"
