#!/bin/bash

if [ -z ${SUMO_NAME} ] || [ -z ${SUMO_CATEGORY} ]; then
    echo "SUMO_NAME or SUMO_CATEGORY environment variable(s) not set, exiting"
    exit 1
fi 

if [ ! -z ${SUMO_HOSTNAME} ]; then
    SUMO_HOSTNAME_LINE=$'\n'"            \"hostName\":\"${SUMO_HOSTNAME}\","
fi

if [  "true" != "${MULTILINE_PROCESSING}" ]; then
    MULTILINE_PROCESSING="false"
fi

if [ -z $PATH_EXPRESSION ]; then
    PATH_EXPRESSION="/tmp/clogs/**/*.log"
fi

echo "Writing /etc/sumo-sources.json:"

cat >/etc/sumo-sources.json <<EOL
{
    "api.version": "v1",
    "sources": [
        {
            "sourceType": "LocalFile",
            "name": "${SUMO_NAME}",
            "pathExpression": "$PATH_EXPRESSION",
            "category": "${SUMO_CATEGORY}",${SUMO_HOSTNAME_LINE}
            "useAutolineMatching": "${MULTILINE_PROCESSING}",
            "multilineProcessingEnabled": "${MULTILINE_PROCESSING}"
        }
    ]
}
EOL

echo "Starting sumologic..."
echo "=================CONFIG==================="
echo "SUMO_NAME            $SUMO_NAME"
echo "SUMO_HOSTNAME        $SUMO_HOSTNAME"
echo "SUMO_CATEGORY        $SUMO_CATEGORY"
echo "PATH_EXPRESSION      $PATH_EXPRESSION"
echo "MULTILINE_PROCESSING $MULTILINE_PROCESSING"
echo "=========================================="

source /run.sh "$@"
