FROM        sumologic/collector:latest-syslog
MAINTAINER  BehanceRE <qa-behance@adobe.com>

ADD         ../parameterized-collector /opt/behance/parameterized-collector

ENTRYPOINT  /opt/behance/parameterized-collector
